cp image_temp/image-0011.png selected_images
cp image_temp/image-0017.png selected_images
cp image_temp/image-0029.png selected_images
cp image_temp/image-0030.png selected_images
cp image_temp/image-0058.png selected_images
cp image_temp/image-0063.png selected_images
cp image_temp/image-0072.png selected_images
cp image_temp/image-0097.png selected_images
cp image_temp/image-0168.png selected_images
cp image_temp/image-0218.png selected_images
cp image_temp/image-0219.png selected_images
cp image_temp/image-0239.png selected_images
cp image_temp/image-0275.png selected_images
cp image_temp/image-0276.png selected_images
cp image_temp/image-0284.png selected_images
cp image_temp/image-0292.png selected_images
cp image_temp/image-0296.png selected_images
cp image_temp/image-0297.png selected_images
cp image_temp/image-0321.png selected_images
cp image_temp/image-0322.png selected_images
cp image_temp/image-0348.png selected_images
cp image_temp/image-0354.png selected_images
cp image_temp/image-0357.png selected_images
cp image_temp/image-0366.png selected_images
cp image_temp/image-0388.png selected_images
cp image_temp/image-0431.png selected_images
cp image_temp/image-0518.png selected_images
cp image_temp/image-0528.png selected_images
cp image_temp/image-0697.png selected_images
cp image_temp/image-0723.png selected_images
cp image_temp/image-0742.png selected_images
cp image_temp/image-0783.png selected_images
cp image_temp/image-0787.png selected_images
cp image_temp/image-0825.png selected_images
cp image_temp/image-0827.png selected_images
cp image_temp/image-0828.png selected_images
cp image_temp/image-0838.png selected_images
cp image_temp/image-0843.png selected_images
cp image_temp/image-0844.png selected_images
cp image_temp/image-0851.png selected_images
cp image_temp/image-0852.png selected_images
cp image_temp/image-0864.png selected_images
cp image_temp/image-0865.png selected_images
cp image_temp/image-0901.png selected_images
cp image_temp/image-0918.png selected_images
cp image_temp/image-0919.png selected_images
cp image_temp/image-0928.png selected_images
