cp image_temp/image-0102.png selected_images
cp image_temp/image-0110.png selected_images
cp image_temp/image-0113.png selected_images
cp image_temp/image-0114.png selected_images
cp image_temp/image-0119.png selected_images
cp image_temp/image-0127.png selected_images
cp image_temp/image-0129.png selected_images
cp image_temp/image-0132.png selected_images
cp image_temp/image-0206.png selected_images
cp image_temp/image-0208.png selected_images
cp image_temp/image-0263.png selected_images
cp image_temp/image-0266.png selected_images
cp image_temp/image-0267.png selected_images
cp image_temp/image-0326.png selected_images
cp image_temp/image-0365.png selected_images
cp image_temp/image-0373.png selected_images
cp image_temp/image-0375.png selected_images
cp image_temp/image-0382.png selected_images
cp image_temp/image-0385.png selected_images
cp image_temp/image-0390.png selected_images
cp image_temp/image-0393.png selected_images
cp image_temp/image-0429.png selected_images
cp image_temp/image-0431.png selected_images
